apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-auth-server
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jwt-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: jwt-auth/app
        property: jwt_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: auth-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: jwt-auth/db
        property: username
    - secretKey: password
      remoteRef:
        key: jwt-auth/db
        property: password
    - secretKey: database
      remoteRef:
        key: jwt-auth/db
        property: database
