apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: greenhouse-iot
  description: EMQX IoT simulator stack
  annotations:
    github.com/project-slug: zazanicholas01/greenhouse-iot
    backstage.io/kubernetes-id: greenhouse-iot
    backstage.io/kubernetes-namespace: iot-playground
spec:
  type: service
  lifecycle: production
  owner: platform-team
