apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: lan-pool
spec:
  blocks:
  - cidr: "192.168.1.240/28"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lan-l2
spec:
  # optional: restrict which services get announced (otherwise all eligible services)
  # serviceSelector:
  #   matchLabels:
  #     expose: "lan"

  # choose which NIC(s) on the node(s) should answer ARP/NDP
  interfaces:
  - "^eth0$"

  externalIPs: true
  loadBalancerIPs: true