apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: playground-manifests
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/Zazanicholas01/auth-playground.git
  secretRef:
    name: playground-manifests