apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: libvirt-l2
spec:
  serviceSelector: {}
  nodeSelector: {}
  interfaces:
    - ^ens3$
  loadBalancerIPs: true
  externalIPs: true
