apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: demo-realm
  namespace: keycloak
spec:
  keycloakCRName: demo-keycloak
  realm:
    id: demo
    realm: demo
    enabled: true
    displayName: Demo Realm
    identityProviders:
      - alias: github
        providerId: github
        enabled: true
        trustEmail: true
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: "Ov23liQieIS8ufWc6afo"
          clientSecret: "d3761e4f585a8148801fc357a2be4c6dd15fbcc4"
          userInfoUrl: "https://api.github.com/user"
          authorizationUrl: "https://github.com/login/oauth/authorize"
          tokenUrl: "https://github.com/login/oauth/access_token"
          defaultScope: "read:user user:email"
          
    clients:
      - clientId: demo-app
        enabled: true
        publicClient: true
        redirectUris:
          - "http://localhost:3000/*"
        webOrigins:
          - "*"
      
      - clientId: oidc-demo-web
        name: OIDC Demo Web
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: password123
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        redirectUris:
          - "https://oidclab.local:8443/api/auth/oidc/callback"
        webOrigins:
          - "https://oidclab.local:8443"
