// Automatically generated by astro-icon
// 8259ec9c6007e3de62fd39c231a0384a7d96f3eb7662eb0d973834a0d4e27c81

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-path"
		| "circle-stack"
		| "globe"
		| "map-pin"
		| "server"
		| "shield-check";
}