apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator
  namespace: iot-playground
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-simulator
  template:
    metadata:
      labels:
        app: iot-simulator
    spec:
      containers:
        - name: simulator
          image: ghcr.io/zazanicholas01/greenhouse-iot-simulator:run-8 # {"$imagepolicy": "flux-system:greenhouse-iot-simulator"}
          imagePullPolicy: Always
          command: ["bun", "run", "index.js"]
          env:
            - name: MQTT_URL
              value: mqtt://emqx-listeners:1883
            - name: MQTT_TOPIC_ROOT
              value: site/alpha/devices
            - name: PUBLISH_INTERVAL_MS
              value: "2000"
            - name: SCENARIO
              value: baseline-day
            - name: SIMULATOR_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: iot-simulator
  namespace: iot-playground
spec:
  selector:
    app: iot-simulator
  ports:
    - name: http
      port: 8080
      targetPort: 8080
