apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-ui
  namespace: iot-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-ui
  template:
    metadata:
      labels:
        app: iot-ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/zazanicholas01/greenhouse-iot-ui:run-37 # {"$imagepolicy": "flux-system:greenhouse-iot-ui"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: UI_PORT
              value: "8080"
            - name: API_BASE
              value: http://iot-api:8080
---
apiVersion: v1
kind: Service
metadata:
  name: iot-ui
  namespace: iot-playground
spec:
  selector:
    app: iot-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
