apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-ui
  namespace: iot-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-ui
  template:
    metadata:
      labels:
        app: iot-ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/zazanicholas01/greenhouse-iot-ui:run-40 # {"$imagepolicy": "flux-system:greenhouse-iot-ui"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: UI_PORT
              value: "8080"
            - name: IOT_API_BASE
              value: http://iot-api:8080
            - name: IOT_SIMULATOR_BASE
              value: http://iot-simulator:8080
            - name: IOT_GRAFANA_BASE
              value: http://grafana:3000
            - name: IOT_DBGATE_BASE
              value: http://dbgate:3000
            - name: IOT_AUTH_BASE
              value: http://iot-jwt-auth-service
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: iot-jwt-auth-secret
                  key: jwt-secret
            - name: JWT_ISSUER
              value: "iot.local"
            - name: JWT_AUDIENCE
              value: "iot-ui"
---
apiVersion: v1
kind: Service
metadata:
  name: iot-ui
  namespace: iot-playground
spec:
  selector:
    app: iot-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
