from __future__ import annotations

from typing import Protocol, Any

class TelemetryRepository(Protocol):
    async def load_device_states(self) -> dict[str, dict]: ...
    async def recent_events(self, limit: int) -> list[dict[str, Any]]: ...
    async def telemetry_history(self, device_id: str, limit: int) -> list[dict[str, Any]]: ...
    async def load_recent_alerts(self, limit: int) -> list[dict[str, Any]]: ...
    async def load_gold_fleet_summary(self) -> dict[str, Any] | None: ...
    async def load_gold_zone_health(self) -> list[dict[str, Any]]: ...
    async def load_gold_alert_counts(self, limit: int) -> list[dict[str, Any]]: ...
    async def load_gold_zone_metrics(self, limit: int) -> list[dict[str, Any]]: ...
    async def persist_bronze_event(self, event: dict[str, Any]) -> None: ...
    async def persist_bronze_telemetry(self, topic: str, normalized: dict[str, Any]) -> None: ...
    async def upsert_device_state(self, device: dict[str, Any]) -> None: ...


class SyntheticGateway(Protocol):
    def materialize_devices(self, source_devices: dict[str, dict]) -> list[dict[str, Any]]: ...
    def synthetic_history_for(self, device_id: str) -> list[dict[str, Any]]: ...


class HealthGateway(Protocol):
    async def is_db_connected(self) -> bool: ...


class MqttStatusGateway(Protocol):
    @property
    def connected(self) -> bool: ...