apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot-playground

resources:
  - namespace.yaml
  - emqx/emqx.yaml
  - emqx/emqx-route.yaml
#  - emqx/mqtt-tcp-route.yaml
  - simulator/api.yaml
  - simulator/simulator.yaml
  - simulator/ui-client.yaml
  - simulator/simulator-route.yaml
  - config.yaml
  - simulator/timescaledb.yaml
  - simulator/dbgate.yaml
  - simulator/bronze-silver-cron.yaml

configMapGenerator:
  - name: iot-api-code
    files:
      - simulator/api/index.js
  - name: iot-sql-scripts
    files:
      - simulator/sql/promote-bronze-to-silver.sql
  - name: iot-timescaledb-init
    files:
      - simulator/sql/init.sql