apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iot-playground

resources:
  - emqx/emqx.yaml
  - emqx/emqx-route.yaml
#  - emqx/mqtt-tcp-route.yaml
  - simulator/api.yaml
  - simulator/simulator.yaml
  - simulator/ui-client.yaml
  - simulator/simulator-route.yaml
  - config.yaml
  - simulator/timescaledb.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
#   - name: iot-ui-code
#     files:
#       - simulator/ui/index.html
#       - simulator/ui/styles.css
#       - simulator/ui/index.js
#       - simulator/ui/server.js
#       - simulator/ui/dev-assets/greenhouse-twin.png
