name: Build and Deploy Greenhouse API

on:
  push:
    branches:
      - main
    paths:
      - "manifests/emqx-iot/simulator/api/**"
      - ".github/workflows/deploy-greenhouse-api.yaml"

permissions:
  packages: write

env:
  IMAGE_NAME: zazanicholas01/greenhouse-iot-api

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image tags
        env:
          IMAGE_SHA: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          IMAGE_LATEST: ghcr.io/${{ env.IMAGE_NAME }}:latest
          IMAGE_RUN: ghcr.io/${{ env.IMAGE_NAME }}:run-${{ github.run_id }}
        run: |
          docker build \
            -f manifests/emqx-iot/simulator/api/Dockerfile \
            -t "$IMAGE_SHA" \
            -t "$IMAGE_LATEST" \
            -t "$IMAGE_RUN" \
            manifests/emqx-iot/simulator/api

          docker push "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"
          docker push "$IMAGE_RUN"
